version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: pinchin-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_PORT=${PORT}
    volumes:
      - mysqldb:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PORT}:3306
volumes:
  mysqldb: